[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ai-poc",
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.52.0",
]

[tool.uv.sources]
ai-poc = { workspace = true }

[tool.setuptools.packages.find]
include = ["app*"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"